"""Offline verification harness — run the FULL pipeline on LIVE feeds without
an Anthropic API key, by stubbing only the Claude calls with a deterministic
keyword-based scorer + template summaries.

This is a developer/CI smoke test for the ingest -> dedup -> compose -> dry-run
path. It is NOT part of the shipped product; the real run uses Claude via the
`Curator` in ai_pulse.curate. Run:  python scripts/offline_dryrun.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ai_pulse.config import load_config            # noqa: E402
from ai_pulse.curate import Curator                # noqa: E402
from ai_pulse.logging_setup import setup_logging   # noqa: E402
from ai_pulse.models import CuratedItem            # noqa: E402
from ai_pulse.pipeline import run_phase_a          # noqa: E402


class StubCurator(Curator):
    """Deterministic stand-in for Claude: keyword scoring + template prose."""

    def score_candidates(self, articles):
        kws = [k.lower() for t in self.cfg.context_profile.themes for k in t.keywords]
        scored = []
        for a in articles:
            blob = f"{a.title} {a.summary_raw}".lower()
            hits = sum(1 for k in kws if k in blob)
            base = min(10, 4 + hits)               # 4..10
            scored.append((a, round(min(10, base * a.weight))))
        scored.sort(key=lambda t: t[1], reverse=True)
        return scored

    def summarise(self, selected):
        items = []
        for a, score in selected:
            snippet = (a.summary_raw or a.title)[:160].strip()
            items.append(CuratedItem(
                title=a.title, url=a.url, source_name=a.source_name,
                published_iso=a.published.isoformat(),
                summary=f"{snippet}." if snippet else a.title,
                why_it_matters="(stubbed) Relevant to Tamkeen's AI awareness.",
                relevance=score,
            ))
        note = ("This week's edition was generated by the offline verification "
                "harness (Claude stubbed). Summaries are placeholders.")
        return items, note, 0


def main() -> int:
    cfg = load_config("config.yaml")
    setup_logging(cfg.storage.log_dir, cfg.storage.log_level)
    digest, report = run_phase_a(cfg, dry_run=True, curator=StubCurator(cfg.curate))
    return 0 if digest else 1


if __name__ == "__main__":
    raise SystemExit(main())
